### ISSUE TITLE
Device testing

### ISSUE THREAD

**Issue by gabrielflorit** [BostonGlobe/elections-2016#193]
- [x] Android
- [x] iPhone
- [x] iPad
- [x] IE
- [x] FF

**Comment by gopperman** [comment]
Applause is handling this, I think we can close this

**Comment by gabrielflorit** [comment]
Well, I don't want to leave QA to someone else, so I'll reopen this. Good reminder to me.

**Comment by gopperman** [comment]
We had Mark and Applause
