### ISSUE TITLE
Test each page with various levels of data integrity

### ISSUE THREAD

**Issue by gabrielflorit** [BostonGlobe/elections-2016#210]

**Comment by gabrielflorit** [comment]
In other words, for each container, see what happens when you hit a:

- bad url,
- good url but no races

**Comment by gopperman** [comment]
Here's a few things that happen in different scenarios:

- If you npm start with a bad api url, everything 500s
- I simulated the API being down (or bad URL) by disconnecting from the VP, got this: 
![image](https://cloud.githubusercontent.com/assets/1591557/20041780/7c05cfb8-a43c-11e6-8274-2dcf664440dc.png)
  - We'll probably need to be less aggressive about needing to fetch the breaking news endpoint
- No races (town/race/office pages): 
![image](https://cloud.githubusercontent.com/assets/1591557/20041816/0178d514-a43d-11e6-974c-32039a5d5fa1.png)
  - we should probably 404 instead

Will close this and create tickets for the other two issues
