### ISSUE TITLE
Make list of urls for rmk to hit

### ISSUE THREAD

**Issue by gabrielflorit** [BostonGlobe/elections-2016#294]
URLS:

/elections/2016
/elections/2016/president
/elections/2016/ma/president
/elections/2016/:officeNameUS
/elections/2016/ma/:officeNameMA
/elections/2016/ma/:officeNameMA/:seatNameMA
/elections/2016/ma/town/:towns

[officeNameUS.txt](https://github.com/BostonGlobe/elections-2016/files/562289/officeNameUS.txt)
[officeNameMA.txt](https://github.com/BostonGlobe/elections-2016/files/562290/officeNameMA.txt)
[seatNameMA.txt](https://github.com/BostonGlobe/elections-2016/files/562307/seatNameMA.txt)
[towns.txt](https://github.com/BostonGlobe/elections-2016/files/562316/towns.txt)

**Comment by gopperman** [comment]
URLS:
- /elections/2016
- /elections/2016/president
  - /elections/2016/president/massachusetts
- /elections/2016/race
  - /elections/2016/race/:officeName
    - /elections/2016/race/:officeName/:seatName
- /elections/2016/town/:townName

I'll attach plaintext files with the full list of the possible parameters

**Comment by gopperman** [comment]
[offices.txt](https://github.com/BostonGlobe/elections-2016/files/556752/offices.txt)

**Comment by gopperman** [comment]
[towns.txt](https://github.com/BostonGlobe/elections-2016/files/556786/towns.txt)

**Comment by tinkerborg** [comment]
Looks good, you can go ahead and close this.
