### ISSUE TITLE
Check with John about the API returning empty races

### ISSUE THREAD

**Issue by gabrielflorit** [BostonGlobe/elections-2016#299]

**Comment by gopperman** [comment]
From John:

> Greg,
After 6am on election day every race should be initialized with zero votes. 
So after that I don't think a valid request should come up empty.
This rings a bell though. Have to think about why we don't 404 when no data is returned.
John

**Comment by gabrielflorit** [comment]
That's good to know.

**Comment by gopperman** [comment]
I think we can close this, open it back up if John returns with additional info
