### ISSUE TITLE
Consider multiple winners (aka commissioners)

### ISSUE THREAD

**Issue by gabrielflorit** [BostonGlobe/elections-2016#336]
- [x] Mention multiple winners in `ResultGroup`
- [x] Style
- [x] Make sure the feed is returning `numWinners`

**Comment by gabrielflorit** [comment]
We should display `numWinners` - the maximum number of allowed winners - if more than 1.

**Comment by gopperman** [comment]
This can be closed, I think. I verified that we have multiple winners covered while doing #357
