### ISSUE TITLE
Consider removing duplicate % / votes copy from ResultGroup

### ISSUE THREAD

**Issue by gabrielflorit** [BostonGlobe/elections-2016#350]

**Comment by enatario** [comment]
Meh. I can see it being maybe good for result bar blocks but the tables are usually so long that it's helpful to have those cues if you don't have the thead for cell reference. At any rate, I think it's mostly a design problem and I've made it so it fits the space across the board

**Comment by gopperman** [comment]
@enatario can this be closed?

**Comment by gabrielflorit** [comment]
not yet, let's leave it here in case we have time

**Comment by gabrielflorit** [comment]
we had time
