### ISSUE TITLE
[Test bug from Applause testing services]

### ISSUE THREAD

**Issue by ApplauseBostonGlobe** [BostonGlobe/elections-2016#359]
View your issue at Applause Testing Services - https://my.applause.com/u/a#!&view=issues&subview=issues&productId=999&bugId=1234
---- ACTION DETAILS ----

Action Performed:
1. Action performed will be placed in here. 
2. Click something

Expected Result:
Expected result will be placed in this field.

Actual Result:
Result will be placed in this field. 
 And even in more than one line.

Additional Info:
Additional information will be placed in this field.

Error Code/Message:
Error code will be placed in this field. Error message will be placed in this field.

---- ENVIRONMENT ----

Environments will be placed in here. Like: Mobile Maker:Apple,Mobile Carrier:T-Mobile United States,Mobile Operating System:iOS,Mobile Model:iPhone 5,Mobile Major Operating System Version:iOS 7.x,Mobile Operating System Version:iOS 7.0.4

Messages will be placed in here. Like:
2015-04-20 12:24:47.0:Hello!
2015-04-20 12:25:06.0:Is it me you're looking for?

---- CUSTOMER NOTES ----

Customer notes will be placed in here. Like:
– My new note  – Tom Sawyer
– Life is like a box of chocolate  – Forrest Gump
------- Browser Context Info ----

Context Info will be placed in here.
---- UTEST PROPERTIES ----

uTest Bug Id: 1234
Component: Component will be placed in here. 
Title: [Test bug from Applause testing services]
Status: New

Type: Functional
Frequency: Every Time
Severity: Low

Product: Product name will be placed in this field.
Test Cycle: Test cycle name will be placed in this field.

---- 1 Community Reproductions ----

Bug Reproductions will be placed in here.
---- 2 Custom Fields ----

Custom fields will be placed in here. Like:
My Field: Some value
Best Field: 42
---- UTEST Attachment ----

Attachments will be placed in here.
![applause.png](http://res.cloudinary.com/crunchbase-production/image/upload/c_pad,h_98,w_98/v1399305715/zmavxi3pemar4kcy1mvd.png)

**Comment by gopperman** [comment]
@ApplauseBostonGlobe Please note a couple of things:

1. We have added a label called "Applause" to the issues tracker. Please add this label as well as the "Bug" label on all issues you file.

2. You can place attachments directly in the comments in github, try it out.

Thanks for your help everyone!
