### ISSUE TITLE
Inconsistency - "Elections 2016" vs "Election 2016"

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#362]
The page name is "Elections 2016" but the header title says "Election 2016" 

Can we pick one - with or without the "s"?

http://screencast.com/t/dhqP0HzvH2q

**Comment by gopperman** [comment]
![image](https://cloud.githubusercontent.com/assets/1591557/19905005/5b952994-a04b-11e6-86df-74809b778748.png)
