### ISSUE TITLE
Tweak BoP Legend

### ISSUE THREAD

**Issue by gabrielflorit** [BostonGlobe/elections-2016#370]
Is there a way to place all elements on the same line for large breakpoints?
![screen shot 2016-11-01 at 7 52 46 pm](https://cloud.githubusercontent.com/assets/370976/19911881/e4cc48b6-a06c-11e6-81cd-52db30f4004f.png)

**Comment by enatario** [comment]
no need b/c i constrained the size of it on the us senate page
