### ISSUE TITLE
Swing states scroll into view w/o legend explaining colors + gradient

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#379]
Legend displays lower on the page. User will see swing states without explanation of colors and/or gradients

![image](https://cloud.githubusercontent.com/assets/16842687/19943092/66165f48-a10c-11e6-9648-c6dcc777d96b.png)

**Comment by gabrielflorit** [comment]
Good point

**Comment by gabrielflorit** [comment]
done
