### ISSUE TITLE
Tease text for Town search

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#385]
Desktop users may not immediately recognize that they have the ability to type in the town search box. This may be frustrating for users looking for towns at the end of the alphabet and scroll too far... 

Currently, the text shows "Select a town..." is it worth exploring some additonal text to let users know that they can type in the box too? 

Here's a video where I play the role of an impatient Yarmouth resident with a tendency to scroll very, very aggressively: http://screencast.com/t/xJC4lN8hk

**Comment by enatario** [comment]
oh shit good catch. i usually try to never leave a form input without a label companion.

**Comment by enatario** [comment]
ref: https://github.com/BostonGlobe/elections-2016/issues/388

**Comment by gabrielflorit** [comment]
won't fix
