### ISSUE TITLE
Styling of dropdown arrow on "Select a state" in Firefox

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#387]
The dropdown arrow item looks different on firefox... kind of Windows 95-ish

![image](https://cloud.githubusercontent.com/assets/16842687/19978673/16d7bd60-a1ce-11e6-80bb-6311b273f91b.png)

**Comment by enatario** [comment]
Styling form elements tends to be difficult. Basically it's very hard to override each browsers default settings for input fields to make it look uniform across the board. It can result in some jankiness. Additionally, I err on the side of keeping form elements like drowpdowns relatively native to align with user expectation.
