### ISSUE TITLE
Fuzzy search UX observation on desktop

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#388]
On desktop - a user clicks "Town Results" and starts typing - nothing happens. Typed searches only work if a user clicks "Select a town..." field. In summary, the user must click twice in order to begin entering text. 

On mobile - it's more apparent for the user because the native keyboard launches only after tapping "Select a town"

**Comment by gabrielflorit** [comment]
@mgellis not sure I can replicate this. When I start typing I get autocompletion.

**Comment by enatario** [comment]
@gabrielflorit i think matt is saying that it takes another click to get to autocomplete. so i have to click on the nav item, and _then_ click on the select bar to type things in. We can look into autofocusing the input element if the drawer is open.

**Comment by gabrielflorit** [comment]
superceded by https://github.com/BostonGlobe/elections-2016/issues/385
