### ISSUE TITLE
Editorial request: Add :15 counter to homepage

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#448]
We don't have any type of counter for when the homepage will be updated next -- I think we need that. It doesn't have to be every 15 secs, but we need to show people when the next update is coming. That has always been a huge thing for readers, as we saw in particular during the primaries.

**Comment by gabrielflorit** [comment]
it's there, but all results are in. so that's why you don't see it.

**Comment by gabrielflorit** [comment]
done
