### ISSUE TITLE
Editorial request: Remove map drop down list on desktop

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#449]
The drop-down list seems a little unnecessary on desktop, because we have the clickable map, and when I pick a state it doesn't work because I hit the hover map underneath.

This was noted by Applause, as well. As soon as a user selects a state, the tooltip updates to whichever state their mouse is on.

**Comment by gabrielflorit** [comment]
we worked around this by having a two-col layout on larger screens
