### ISSUE TITLE
Editorial request: Apps paywall - add "Already a subscriber? Sign in" 

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#452]
On this sign-in page for apps, when I click the "Already a subscriber? Sign in" option it brings me back to the homepage. Are we sure the apps paywall is working properly? Could be a dev thing.

**Comment by enatario** [comment]
I think you may be hitting a 404ed homepage because it redirects to what will be the live link `http://www.bostonglobe.com/elections/2016/`. But we'll recheck on pre-prod.

**Comment by gabrielflorit** [comment]
Duplicate of https://github.com/BostonGlobe/elections-2016/issues/375
