### ISSUE TITLE
How should we handle 404s?

### ISSUE THREAD

**Issue by gabrielflorit** [BostonGlobe/elections-2016#465]

**Comment by enatario** [comment]
as much as i like silly 404s, we should probably work to be user-friendly. So a simple message with the nav links but in a more prominent form.

**Comment by gabrielflorit** [comment]
good idea.

**Comment by gopperman** [comment]
Related to #210:
![image](https://cloud.githubusercontent.com/assets/1591557/20041816/0178d514-a43d-11e6-974c-32039a5d5fa1.png)
