### ISSUE TITLE
Preview image for og and twitter

### ISSUE THREAD

**Issue by gopperman** [BostonGlobe/elections-2016#466]
Send me something I can add to meta.json
![image](https://cloud.githubusercontent.com/assets/1591557/20034348/fdbbed5a-a390-11e6-8824-61ccd1d34b18.png)

Related to #286

**Comment by enatario** [comment]
how bout this

![giphy](https://cloud.githubusercontent.com/assets/2642348/20034839/79999910-a3a3-11e6-8382-a1dea8a67b00.gif)

**Comment by gopperman** [comment]
i wish
