### ISSUE TITLE
App bombs when API or Breaking news fetch fails

### ISSUE THREAD

**Issue by gopperman** [BostonGlobe/elections-2016#475]
![image](https://cloud.githubusercontent.com/assets/1591557/20041780/7c05cfb8-a43c-11e6-8274-2dcf664440dc.png)

**Comment by gabrielflorit** [comment]
not anymore

**Comment by gopperman** [comment]
https://www.youtube.com/watch?v=2DRvm61EVyI

**Comment by franchitto** [comment]
the breaking bar loads with page then dissappears quickly...i guess this is known?

**Comment by gopperman** [comment]
yes should not be an issue on prod
