### ISSUE TITLE
Add tagging to social

### ISSUE THREAD

**Issue by gabrielflorit** [BostonGlobe/elections-2016#479]

**Comment by gopperman** [comment]
Rob says there's basic exit tracking coming through already. But if we need to reopen, here's the code:

var s=s_gi('nytbostonglobecom');
s.linkTrackVars='eVar15,channel,prop1,prop6,prop43';
s.linkTrackEvents='none';
s.tl(this,'o', 'Apps - General Election 2016 - Twitter');
