### ISSUE TITLE
Display issues with US map on President and Election Central pages

### ISSUE THREAD

**Issue by michaelworkman** [BostonGlobe/elections-2016#483]
Candidate names breaking into second line on multiple states, desktop and mobile.

Also, for Nevada make the fourth category be "Others" instead of "None of these candidates".

![nevada](https://cloud.githubusercontent.com/assets/1630903/20067702/41a1f920-a4e4-11e6-85b1-211c631bcf3f.jpg)

**Comment by enatario** [comment]
Known issue. Being fixed: https://github.com/BostonGlobe/elections-2016/issues/459
