### ISSUE TITLE
Breaking News signup at bottom near footer...wrong target

### ISSUE THREAD

**Issue by franchitto** [BostonGlobe/elections-2016#487]

**Comment by franchitto** [comment]
![image](https://cloud.githubusercontent.com/assets/9949147/20070720/7deff048-a4ef-11e6-8194-3b6b58cfd21c.png)

current target = http://elections.dev.passenger.bostonglobe.com/elections/2016#

expected target = ?

**Comment by michaelworkman** [comment]
I vote for http://pages.email.bostonglobe.com/BreakingNewsSignUp/

**Comment by franchitto** [comment]
verified fix and that email is making it into the db
