### ISSUE TITLE
Clean up abbreviations in Mass results

### ISSUE THREAD

**Issue by michaelworkman** [BostonGlobe/elections-2016#488]
Still a lot of abbreviations on the Mass House and Senate pages. Example:

![screen shot 2016-11-07 at 2 05 07 pm](https://cloud.githubusercontent.com/assets/1630903/20071675/63a95d1a-a4f3-11e6-8fd8-69ca346cda73.png)

**Comment by gopperman** [comment]
I think this was the result of the AP test reinitializing things. It is fixed now.
