### ISSUE TITLE
Balance of power not showing 

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#489]
BOP showing as blank on Election 2016 page

![image](https://cloud.githubusercontent.com/assets/16842687/20071757/af27b20a-a4f3-11e6-97bc-d580f0a9e1dc.png)

URL: http://elections.dev.passenger.bostonglobe.com/elections/2016?p1=BG_election_nav_central

**Comment by gabrielflorit** [comment]
closed by https://github.com/BostonGlobe/elections-2016/commit/70ae4c94afebfea19b112d0b5c39cddd75a88af7
