### ISSUE TITLE
Copy on social connect modal 

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#493]
Are users signing up for Breaking News AND Today's Headlines? This is how the social connect works on the rest of the sight

Apps
![image](https://cloud.githubusercontent.com/assets/16842687/20072645/299c2ab8-a4f7-11e6-8daf-1fab99c4e0f8.png)

Rest of site
![image](https://cloud.githubusercontent.com/assets/16842687/20072667/43201b20-a4f7-11e6-8fcb-f41bb91b1f75.png)

**Comment by gabrielflorit** [comment]
our modal is the one we use on apps - copy changes might involve a lot of work.
