### ISSUE TITLE
Should we be abbreviating states in the results bar?

### ISSUE THREAD

**Issue by gopperman** [BostonGlobe/elections-2016#497]
Looks weird here: 
![image](https://cloud.githubusercontent.com/assets/1591557/20074357/e46e7fe8-a4fd-11e6-9b1f-8a34730bbab2.png)

If we should keep it the same, close this. If we should change it, assign it back to me.

**Comment by enatario** [comment]
Conferred with @michaelworkman . Let's use the full in the results bar. This makes me think I should audit and add tickets for `abbr` tags for other abbreviations that we haven't marked
