### ISSUE TITLE
Will editorial be able to use interactive MA map on article pages?

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#505]
can we extract the town by town map to show how each voted for each of the questions, pot, charter schools, etc? this component might support an editorial that’s examining where the question failed. liberals in the suburbs voted it down but it doesn’t pertain to them? here’s the component we might want to pull for this type of analysis:  http://elections.dev.passenger.bostonglobe.com/elections/2016/MA/Question/2%20-%20Expand%20Charter%20Schools?p1=BG_election_full_results

![image](https://cloud.githubusercontent.com/assets/16842687/20076920/3bdaa77a-a508-11e6-88a0-db95821b527c.png)

**Comment by gabrielflorit** [comment]
maybe.
