### ISSUE TITLE
The active state on our breaking news signup button is unreadable

### ISSUE THREAD

**Issue by gopperman** [BostonGlobe/elections-2016#512]
1. Click the button
2. Return to page
3. ...
![image](https://cloud.githubusercontent.com/assets/1591557/20082041/4c68227a-a521-11e6-9154-0f503867fb78.png)

**Comment by gopperman** [comment]
wow that was a pretty big typo

**Comment by enatario** [comment]
thought i fixed that. turns out it's a problem on focus not active
