### ISSUE TITLE
Will Facebook or Twitter pick up an image + header if a user shares an elections URL?

### ISSUE THREAD

**Issue by mgellis** [BostonGlobe/elections-2016#519]
Will Facebook or Twitter pick up an image + header if a user shares an elections URL?

From Jason (although this is a dev page) 
![image](https://cloud.githubusercontent.com/assets/16842687/20084844/02e4f634-a533-11e6-849c-18cfe92349b0.png)

**Comment by gabrielflorit** [comment]
yes
