### ISSUE TITLE
Time not showing on breaking bar on phone

### ISSUE THREAD

**Issue by michaelworkman** [BostonGlobe/elections-2016#528]
Time not showing. iPhone 6, iOS 10.

![img_0296](https://cloud.githubusercontent.com/assets/1630903/20107385/650dd862-a5a6-11e6-86da-32220e231e73.PNG)

**Comment by gabrielflorit** [comment]
won't display time anymore, see why here https://github.com/BostonGlobe/elections-2016/commit/63e007aa7393f2cfc59193f8ba95c543fdf8d1ad

**Comment by franchitto** [comment]
verified on 10.01 too and here are the % of mobile traffic for this
![image](https://cloud.githubusercontent.com/assets/9949147/20109108/a16ff2b2-a5ac-11e6-9253-f5e8113e545a.png)
